services:
  - type: web
    name: todo-app
    runtime: node
    rootDir: todo-app
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
